export const SET_VIDEOGAMES = "SET_VIDEOGAMES";
export const SET_VIDEOGAMES_NAME = "SET_VIDEOGAMES_NAME";
export const SET_VIDEOGAMES_GENRE = "SET_VIDEOGAMES_GENRE";
export const SET_VIDEOGAME_DETAIL = "SET_VIDEOGAME_DETAIL";
export const SET_GENRES = "SET_GENRES";