export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME";
export const SET_VIDEOGAMES = "SET_VIDEOGAMES";
export const SET_VIDEOGAMES_NAME = "SET_VIDEOGAMES_NAME";
export const SET_VIDEOGAMES_GENRE = "SET_VIDEOGAMES_GENRE";
export const SET_VIDEOGAMES_SORT = "SET_VIDEOGAMES_SORT";
export const SET_VIDEOGAME_DETAIL = "SET_VIDEOGAME_DETAIL";
export const SET_GENRES = "SET_GENRES";
export const SET_PLATFORMS = "SET_PLATFORMS";